/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estadonacion;


import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author XPC
 */
public class Heredia extends javax.swing.JDialog {

  /**
   * Creates new form Heredia
   */
  public Heredia(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    cargarImagen();
    difuminarBotones();
  }
  
  public Heredia(){
    initComponents();
    cargarImagen();
    difuminarBotones();
  }
  
  public void difuminarBotones(){
    ArrayList<JButton> botones = new ArrayList<JButton>();
    botones.add(b1);
    botones.add(b2);
    botones.add(b3);
    botones.add(b4);
    botones.add(b5);
    botones.add(b6);
    botones.add(b7);
    botones.add(b8);
    botones.add(b9);
    botones.add(b10);
    for(JButton boton: botones){
      boton.setOpaque(false);
      boton.setContentAreaFilled(false);
      boton.setBorderPainted(false);
    }
  }
  
    public void abrirInformacion(String canton){
      Informacion i = new Informacion("Heredia", canton);
      System.out.println(canton);
      i.setVisible(true);
      this.dispose();  
  }
  
  public void cargarImagen(){
    informacion.setText("<html>Reporte Cantonal de Provincia Heredia<br/>"
            + "Lista de Provincias: <br/><br/>1. Sarapiquí<br/>2. Heredia"
            + "<br/>3. Barba<br/>4. Santa Bárbara<br/>5. Flores<br/>6. San Rafael"
            + "<br/>7. San Isídro<br/>8. Santo Domingo<br/>9. Belén<br/>10. San Pablo</html>");
    ImageIcon imagen;
    imagen = new ImageIcon("C:\\Users\\XPC\\Desktop\\EstadoNacion\\Heredia.gif");
    mapa.setIcon(imagen);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        mapa = new javax.swing.JLabel();
        informacion = new javax.swing.JLabel();
        exit1 = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        Fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        b1.setText("SARAPIQUÍ");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 130, 70));

        b2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        b2.setText("HEREDIA");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 110, 30));

        b3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        b3.setText("BARBA");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 80, -1));

        b4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        b4.setText("SANTA BÁRBARA");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 130, -1));

        b5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        b5.setText("SAN RAFAEL");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 110, -1));

        b6.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        b6.setText("SAN ISIDRO");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 110, 20));

        b7.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        b7.setText("SANTO DOMINGO");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 140, 20));

        b8.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        b8.setText("SAN PABLO");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, -1, -1));

        b9.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        b9.setText("BELÉN");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, 80, 30));

        b10.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        b10.setText("FLORES");
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        getContentPane().add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 80, 20));

        mapa.setIcon(new javax.swing.ImageIcon("C:\\Users\\XPC\\Desktop\\EstadoNacion\\Heredia.gif")); // NOI18N
        getContentPane().add(mapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 475, 596));

        informacion.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        getContentPane().add(informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 490, 510));

        exit1.setBackground(new java.awt.Color(0, 204, 51));
        exit1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit1.setForeground(new java.awt.Color(255, 255, 255));
        exit1.setText("Atrás");
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        getContentPane().add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 70, 30));

        exit.setBackground(new java.awt.Color(153, 0, 0));
        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 50, 30));

        titulo.setFont(new java.awt.Font("NSimSun", 1, 58)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("HEREDIA");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 400, 140));

        Fondo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\XPC\\Desktop\\EstadoNacion\\blue.jpg")); // NOI18N
        getContentPane().add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
    // TODO add your handling code here:
    this.dispose();
    Provincias p = new Provincias();
    p.setVisible(true);
  }//GEN-LAST:event_exit1ActionPerformed

  private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
    // TODO add your handling code here:
    System.exit(0);
  }//GEN-LAST:event_exitActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        abrirInformacion(b1.getText());
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        abrirInformacion(b2.getText());
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        abrirInformacion(b3.getText());
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        abrirInformacion(b4.getText());
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        abrirInformacion(b5.getText());
    }//GEN-LAST:event_b5ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
        abrirInformacion(b10.getText());
    }//GEN-LAST:event_b10ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        abrirInformacion(b6.getText());
    }//GEN-LAST:event_b6ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        abrirInformacion(b9.getText());
    }//GEN-LAST:event_b9ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        abrirInformacion(b8.getText());
    }//GEN-LAST:event_b8ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        abrirInformacion(b7.getText());
    }//GEN-LAST:event_b7ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Heredia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Heredia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Heredia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Heredia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        Heredia dialog = new Heredia(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo1;
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton exit;
    private javax.swing.JButton exit1;
    private javax.swing.JLabel informacion;
    private javax.swing.JLabel mapa;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
