/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estadonacion;

import java.util.ResourceBundle;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import static javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER;
import jdk.nashorn.internal.parser.JSONParser;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;
import org.icepdf.ri.util.PropertiesManager;

/**
 *
 * @author XPC
 */
public class Informacion extends javax.swing.JDialog {

  /**
   * Creates new form Informacion
   */
  public Informacion(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();

  }

  public Informacion(String provincia, String canton) {
    initComponents();
    this.provincia = provincia;
    this.canton = canton;
    titulo.setText(canton + "   : " + provincia);
    cargarPDF(canton, provincia);
  }

  public void cargarPDF(String canton, String provincia) {
    // Get a file from the command line to open
    String filePath = "C:\\Users\\XPC\\Desktop\\EstadoNacion\\Cantones\\"+provincia+"\\"+canton+".pdf";

    // build a controller
    SwingController controller = new SwingController();

    PropertiesManager properties
            = new PropertiesManager(System.getProperties(),
                    ResourceBundle.getBundle(PropertiesManager.DEFAULT_MESSAGE_BUNDLE));

    // Change the value of a couple default viewer Properties.
    // Note: this should be done before the factory is initialized.
    properties.setBoolean(PropertiesManager.PROPERTY_SHOW_TOOLBAR_ANNOTATION,
            Boolean.FALSE);
    properties.setBoolean(PropertiesManager.PROPERTY_SHOW_TOOLBAR_FIT,
            Boolean.FALSE);
    properties.setBoolean("application.toolbar.show.annotation",
            Boolean.FALSE);
    properties.setBoolean("application.toolbar.show.rotate",
            Boolean.FALSE);
    properties.setBoolean("application.toolbar.show.fit",
            Boolean.FALSE);
    properties.setBoolean("application.toolbar.show.zoom",
            Boolean.FALSE);
    properties.setBoolean("application.toolbar.show.utility",
            Boolean.FALSE);
    properties.setBoolean("application.viewerpreferences.fitwindow ",
            Boolean.FALSE);
    properties.setFloat("application.zoom.factor.default", new Float(2.0));
    // Build a SwingViewFactory configured with the controller
    SwingViewBuilder factory = new SwingViewBuilder(controller, properties);
    
    

    // Use the factory to build a JPanel that is pre-configured
    //with a complete, active Viewer UI.
    JPanel viewerComponentPanel = factory.buildViewerPanel();
    
    viewerComponentPanel.setPreferredSize(panel.getSize());

    
    
    
    // add copy keyboard command
    JScrollPane scroll = new JScrollPane(viewerComponentPanel);
    
    
    scroll.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
    

    ComponentKeyBinding.install(controller, scroll);

    // add interactive mouse link annotation support via callback
    controller.getDocumentViewController().setAnnotationCallback(
            new org.icepdf.ri.common.MyAnnotationCallback(
                    controller.getDocumentViewController()));

    // Create a JFrame to display the panel in
    controller.openDocument(filePath);
    //JFrame window = new JFrame("Using the Viewer Component");
//    this.panel.add(viewerComponentPanel);
    this.panel.add(scroll);
    this.pack();
    this.setVisible(true);

    // Open a PDF document to view
    //controller.openDocument(filePath);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 810, 610));

        exit.setBackground(new java.awt.Color(153, 0, 0));
        exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, 50, 30));

        exit1.setBackground(new java.awt.Color(0, 204, 51));
        exit1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exit1.setForeground(new java.awt.Color(255, 255, 255));
        exit1.setText("Atrás");
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });
        getContentPane().add(exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 70, 30));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 6, 360, 40));

        fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\XPC\\Desktop\\EstadoNacion\\bandera.png")); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
      // TODO add your handling code here:
      System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
      // TODO add your handling code here:
      switch (provincia) {
        case "Puntarenas":
          Puntarenas p = new Puntarenas();
          p.setVisible(true);
          this.dispose();
          break;
        case "Alajuela":
          Alajuela a = new Alajuela();
          a.setVisible(true);
          this.dispose();
          break;
        case "Guanacaste":
          Guanacaste g = new Guanacaste();
          g.setVisible(true);
          this.dispose();
          break;
        case "Heredia":
          Heredia h = new Heredia();
          h.setVisible(true);
          this.dispose();
          break;
        case "Cartago":
          Cartago c = new Cartago();
          c.setVisible(true);
          this.dispose();
          break;
        case "SanJose":
          SanJose s = new SanJose();
          s.setVisible(true);
          this.dispose();
          break;
        case "Limón":
          Limon l = new Limon();
          l.setVisible(true);
          this.dispose();
          break;
        default:
          break;
      }
    }//GEN-LAST:event_exit1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        Informacion dialog = new Informacion(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }
  private String provincia;
  private String canton;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JButton exit1;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
