/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estadonacion;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author XPC
 */
public class Provincias extends javax.swing.JDialog {

  /**
   * Creates new form Provincias
   */
  public Provincias(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    difuminarBotones();
  }
  
  public Provincias(){
    initComponents();
    difuminarBotones();
  }
  
  public void difuminarBotones(){
    instrucciones.setText("<html>Bienvenido al Reporte Cantonal del Estado "
            + "de la Nación.<br/>Para ingresar a un cantón deseado, haga click en la provincia que lo contiene.</html>");
    ArrayList<JButton> botones = new ArrayList<JButton>();
    botones.add(guanacaste);
    botones.add(cartago);
    botones.add(sanJose);
    botones.add(alajuela);
    botones.add(heredia);
    botones.add(puntarenas);
    botones.add(limon);    
    for(JButton boton : botones){
      boton.setOpaque(false);
      boton.setContentAreaFilled(false);
      boton.setBorderPainted(false);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    guanacaste = new javax.swing.JButton();
    alajuela = new javax.swing.JButton();
    heredia = new javax.swing.JButton();
    sanJose = new javax.swing.JButton();
    cartago = new javax.swing.JButton();
    puntarenas = new javax.swing.JButton();
    limon = new javax.swing.JButton();
    exit = new javax.swing.JButton();
    titulo = new javax.swing.JLabel();
    mapa = new javax.swing.JLabel();
    instrucciones = new javax.swing.JLabel();
    background = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setUndecorated(true);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    guanacaste.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        guanacasteActionPerformed(evt);
      }
    });
    getContentPane().add(guanacaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 200, 150));

    alajuela.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        alajuelaActionPerformed(evt);
      }
    });
    getContentPane().add(alajuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 140, 230));

    heredia.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        herediaActionPerformed(evt);
      }
    });
    getContentPane().add(heredia, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 90, 130));

    sanJose.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        sanJoseActionPerformed(evt);
      }
    });
    getContentPane().add(sanJose, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 100, 70));

    cartago.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cartagoActionPerformed(evt);
      }
    });
    getContentPane().add(cartago, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 130, 80));

    puntarenas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        puntarenasActionPerformed(evt);
      }
    });
    getContentPane().add(puntarenas, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 180, 100));

    limon.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        limonActionPerformed(evt);
      }
    });
    getContentPane().add(limon, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 330, 120, 130));

    exit.setBackground(new java.awt.Color(153, 0, 0));
    exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    exit.setForeground(new java.awt.Color(255, 255, 255));
    exit.setText("X");
    exit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        exitActionPerformed(evt);
      }
    });
    getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 20, 60, 30));

    titulo.setFont(new java.awt.Font("NSimSun", 1, 56)); // NOI18N
    titulo.setForeground(new java.awt.Color(255, 255, 255));
    titulo.setText("ESTADO DE LA NACIÓN");
    getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 630, 150));

    mapa.setIcon(new javax.swing.ImageIcon("C:\\Users\\XPC\\Desktop\\EstadoNacion\\CostaRica.png")); // NOI18N
    getContentPane().add(mapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 801, 747));

    instrucciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    getContentPane().add(instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, -1, -1));

    background.setIcon(new javax.swing.ImageIcon("C:\\Users\\XPC\\Desktop\\EstadoNacion\\blue.jpg")); // NOI18N
    getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 770));

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
    // TODO add your handling code here:
    System.exit(0);
  }//GEN-LAST:event_exitActionPerformed

  private void guanacasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guanacasteActionPerformed
    // TODO add your handling code here:
    System.out.println("Guanacaste");
    Guanacaste g = new Guanacaste();
    this.dispose();
    g.setVisible(true);
  }//GEN-LAST:event_guanacasteActionPerformed

  private void alajuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alajuelaActionPerformed
    // TODO add your handling code here:
    System.out.println("Alajuela");
    Alajuela a = new Alajuela();
    this.dispose();
    a.setVisible(true);
  }//GEN-LAST:event_alajuelaActionPerformed

  private void herediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_herediaActionPerformed
    // TODO add your handling code here:
    System.out.println("Heredia");
    Heredia h = new Heredia();
    this.dispose();
    h.setVisible(true);
  }//GEN-LAST:event_herediaActionPerformed

  private void cartagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartagoActionPerformed
    // TODO add your handling code here:
    System.out.println("Cartago");
    Cartago c = new Cartago();
    this.dispose();
    c.setVisible(true);
  }//GEN-LAST:event_cartagoActionPerformed

  private void limonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limonActionPerformed
    // TODO add your handling code here:
    System.out.println("Limon");
    Limon l = new Limon();
    this.dispose();
    l.setVisible(true);
  }//GEN-LAST:event_limonActionPerformed

  private void puntarenasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntarenasActionPerformed
    // TODO add your handling code here:
    System.out.println("Puntarenas");
    Puntarenas p = new Puntarenas();
    this.dispose();
    p.setVisible(true);
  }//GEN-LAST:event_puntarenasActionPerformed

  private void sanJoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanJoseActionPerformed
    // TODO add your handling code here:
    System.out.println("San Jose");
    SanJose sj = new SanJose();
    this.dispose();
    sj.setVisible(true);
  }//GEN-LAST:event_sanJoseActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Provincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Provincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Provincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Provincias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        Provincias dialog = new Provincias(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton alajuela;
  private javax.swing.JLabel background;
  private javax.swing.JButton cartago;
  private javax.swing.JButton exit;
  private javax.swing.JButton guanacaste;
  private javax.swing.JButton heredia;
  private javax.swing.JLabel instrucciones;
  private javax.swing.JButton limon;
  private javax.swing.JLabel mapa;
  private javax.swing.JButton puntarenas;
  private javax.swing.JButton sanJose;
  private javax.swing.JLabel titulo;
  // End of variables declaration//GEN-END:variables
}
